blank_issues_enabled: false
contact_links:
  - name: Join the HyperSystems Discord
    url: https://discord.gg/TqYQgn2ZxM
    about: Come and chat with other players and the HyperSystems team!
  - name: HyperSystems Website
    url: https://hypersystems.dev
    about: Visit our website for more information about HyperSystems.
  - name: HyperPerms Documentation
    url: https://www.hyperperms.com/
    about: Find guides and documentation for HyperPerms.
